#localServer.driverClassName=net.sf.log4jdbc.DriverSpy
#localServer.url=jdbc:log4jdbc:oracle:thin:@www.whalesoft.co.kr:1521:ORCL11
#localServer.username=cms
#localServer.password=cms

#localServer.driverClassName=net.sf.log4jdbc.DriverSpy
#localServer.url=jdbc:log4jdbc:oracle:thin:@www.whalesoft.co.kr:1521:ORCL11
#localServer.username=cms
#localServer.password=cms

#localServer.driverClassName=com.tmax.tibero.jdbc.TbDriver
#localServer.url=jdbc:tibero:thin:@www.whalesoft.co.kr:8669:tibero
#localServer.url=jdbc:tibero:thin:@192.168.0.11:8629:tibero
#localServer.username=gbelib
#localServer.password=gbelib

#tibero\uc5d0\uc11c oracle\ub85c \ubcc0\uacbd
localServer.driverClassName=net.sf.log4jdbc.DriverSpy
#localServer.url=jdbc:log4jdbc:oracle:thin:@192.168.0.63:1521:ORCL11
localServer.url=jdbc:log4jdbc:oracle:thin:@172.16.1.181:1521:ORCL12
localServer.username=gbelib
localServer.password=gbelib

localServer2.driverClassName=net.sf.log4jdbc.DriverSpy
#localServer2.url=jdbc:log4jdbc:oracle:thin:@www.whalesoft.co.kr:1526:ORCL11
localServer2.url=jdbc:log4jdbc:oracle:thin:@192.168.0.11:1521:ORCL11
localServer2.username=gbccs
localServer2.password=gbccsdb12#
#localServer2.username=gbelib3
#localServer2.password=gbelib

localServer3.driverClassName=com.mysql.jdbc.Driver
localServer3.url=jdbc:mysql://localhost:3306/project_ydlib22?autoReconnect=true
localServer3.username=root
localServer3.password=autoset

devServer.driverClassName=oracle.jdbc.driver.OracleDriver
devServer.url=jdbc:oracle:thin:@www.whalesoft.co.kr:1521:ora12
devServer.username=dev1
devServer.password=whalesoft_dev1