localServer.driverClassName=net.sf.log4jdbc.DriverSpy
localServer.url=jdbc:log4jdbc:oracle:thin:@172.16.1.181:1521:ORCL12
localServer.username=gbelib
localServer.password=gbelib

devServer.driverClassName=net.sf.log4jdbc.DriverSpy
devServer.url=jdbc:log4jdbc:oracle:thin:@172.16.1.181:1521:ORCL12
devServer.username=gbelib
devServer.password=gbelib

oracle.net.CONNECT_TIMEOUT=5000
oracle.jdbc.ReadTimeout=10000