@kr.co.whalesoft.app.cms.login

LoginController.login.member_id.NotBlank=ID를 입력하세요.
LoginController.login.member_id.Size=입력하신 ID의 길이가 다릅니다.
LoginController.login.member_pw.NotBlank=페스워드를 입력하세요.
LoginController.login.member_pw.Size=입력하신 PW의 긷이가 맞지 않습니다.